"""updating the inventory table to include the relationships

Revision ID: f4100a3b1d65
Revises: 859e16568b7a
Create Date: 2023-08-02 13:37:23.365517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4100a3b1d65"
down_revision = "859e16568b7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Setting up the foreign key constraint for `inventory_id`
    op.create_foreign_key(None, "order_items", "inventory", ["inventory_id"], ["id"])

    # Setting up the foreign key constraint for `order_id`
    op.create_foreign_key(None, "order_items", "orders", ["order_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Removing the foreign key constraint for `inventory_id`
    op.drop_constraint(None, "order_items", type_="foreignkey")

    # Removing the foreign key constraint for `order_id`
    op.drop_constraint(None, "order_items", type_="foreignkey")

    # ### end Alembic commands ###
